serviceType: "LoadBalancer"
isClusterService: false
servers:
  - zones:
    - zone: .
    port: 53
    plugins:
    - name: errors
    - name: health
      configBlock: |-
        lameduck 5s
    - name: ready
    - name: loop
    - name: reload
    - name: loadbalance
    - name: prometheus
      parameters: 0.0.0.0:9153
    - name: kubernetes
      parameters: cluster.local in-addr.arpa ip6.arpa
      configBlock: |-
        pods insecure
        fallthrough in-addr.arpa ip6.arpa
        ttl 30
    - name: forward
      parameters: . 8.8.8.8
    - name: forward
      parameters: cluster.local /etc/resolv.conf
    - name: cache
      parameters: 30
    - name: etcd
      parameters: kdev.intra
      configBlock: |-
        stubzones
        path /skydns
        endpoint http://etcd-cluster.cluster-system.svc.cluster.local:2379
        fallthrough
prometheus:
  service:
    enabled: false
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "9153"
    selector: {}
  monitor:
    enabled: false
    additionalLabels: {}
    namespace: ""
    interval: ""
    selector: {}