persistentVolumeClaim:
  enabled: true


ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: ca-issuer
  hosts:
    - pihole.kdev.intra
  paths: /
  tls:
    - secretName: pihole-tls
      hosts:
        - pihole.kdev.intra

serviceDns:
    type: LoadBalancer