[general]
# INFO, DEBUG
logging = INFO

[network]
# bridge, calico, cilium, cilium-helm, flannel, kindnet
driver = cilium-helm

# start DNS server in K8S
local_dns_server = true

# docker network
subnet  = 198.18.254.0/24
gateway = 198.18.254.1

# none, cilium
loadbalancer = cilium
# l2, bgp
loadbalancer_mode = bgp
loadbalancer_cidr = 198.18.255.0/24

#api_host = 127.172.50.1
#api_host = kdev
#api_port = 6443

cluster_cidr = 10.0.0.0/16
service_cidr = 10.1.0.0/16

[ingress]
# cilium, nginx, pomerium
driver = pomerium

[service_mesh]
# none, cilium, consule, istio
driver = cilium

# none, cilium, consule, istio
apigateway = none

[registry]
# true or false
enabled = false

port = 6000
rootdirectory = /var/lib/docker-registry

[sso]
# true or false
enabled = true

[kubedash]
# true or false
enabled = true

[monitoring]
# true or false
enabled = false

[observability]
# true or false
enabled = false