[general]
# INFO, DEBUG
logging = INFO

[network]
# flanel, cilium
driver = cilium

# start DNS server in K8S
local_dns_server = true

# docker network
subnet  = 172.50.0.0/16
gateway = 172.50.0.1

# none, cilium
loadbalancer = cilium
# l2, bgp
loadbalancer_mode = bgp
loadbalancer_cidr = 172.51.1.0/24

#api_host = 127.172.50.1
api_host = kind-control-plane
api_port = 6443

cluster_cidr = 10.0.0.0/16
service_cidr = 10.1.0.0/16

[ingress]
# cilium, nginx, pomerium
driver = pomerium

[service_mesh]
# none, cilium, consule
driver = cilium

# none, cilium, consule
apigateway = none

[registry]
# true or false
enabled = false

port = 6000
rootdirectory = /var/lib/docker-registry

[sso]
# true or false
enabled = true

[kubedash]
# true or false
enabled = true

[monitoring]
# true or false
enabled = false

[observability]
# true or false
enabled = false