[general]
# INFO, DEBUG
logging = INFO

[network]
# flanel, cilium
driver = cilium

# registry docker network
subnet  = 172.50.0.0/16
gateway = 172.50.0.1

#api_host = 127.172.50.1
api_host = kind-control-plane
api_port = 6443

cluster_cidr = 10.0.0.0/16
service_cidr = 10.1.0.0/16

# none, cilium
loadbalancer = cilium
# l2, bgp
loadbalancer_mode = l2
loadbalancer_cidr = 10.0.10.0/24

# true, false
mtls = false

[ingress]
# cilium, nginx, pomerium
driver = nginx

# none, cilium
apigateway = none

[monitoring]

enabled = false

[registry]

enabled = true

rootdirectory = "/var/lib/docker-registry"

[sso]

enabled = true