ingress:
  enabled: true
  className: default
  annotations:
    cert-manager.io/cluster-issuer: ca-issuer
  hosts:
    - host: sso.kdev.intra
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - sso.kdev.intra
      secretName: dex-ingress-tls

grpc: 
  enabled: false
certs:
  grpc:
    create: false
  web:
    create: false

config:
  issuer: https://sso.kdev.intra
  storage:
    type: kubernetes
    config:
      inCluster: true
  enablePasswordDB: true
  expiry:
    signingKeys: "4h"
    idTokens: "1h"
  staticPasswords:
    - email: "admin@kdev.intra"
      # bcrypt hash of the string "password": $(echo password | htpasswd -BinC 10 admin | cut -d: -f2)
      hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
      username: "admin"
      userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"
  staticClients:
    - id: oauth2-proxy
      redirectURIs:
        # These redirect URI points to the `--redirect-url` for OAuth2 proxy.
        - 'https://oauth.kdev.intra/oauth2/callback'
      name: 'OAuth2 Proxy'
      secret: "b2F1dGgyLXByb3h5LWNsaWVudC1zZWNyZXQK"
    - id: pomerium
      secret: "y5q5jeEpEmL7aJh74Tgsb32aJz1LaKAh"
      name: "pomerium Static Client"
      redirectURIs:
        - 'https://oauth.kdev.intra/oauth2/callback'
    - id: k8s
      secret: "1Y1BDvwweUiVL89VFePBe5zSMIpI54NM"
      name: 'k8s'
      redirectURIs:
        - 'http://*.kdev.intra/*'
        - 'https://*.kdev.intra/*'
    - id: grafana
      secret: "blLT7cqamLqR9CriDn40gDhChgtRkT4F"
      name: 'grafana'
      redirectURIs:
        - 'http://*.kdev.intra/*'
        - 'https://*.kdev.intra/*'
    - id: kubedash
      secret: "nkBeJzvrBxzRfGNDJENrEvwtnqczGLzk"
      name: 'kubedash'
      redirectURIs:
        - 'http://*.kdev.intra/*'
        - 'https://*.kdev.intra/*'
    - id: vault
      secret: "jjlsKljsfKw9a2nnasvkafm82nLNFE73"
      name: 'vault'
      redirectURIs:
        - 'https://vault.kdev.intra/ui/vault/auth/oidc/oidc/callback'
        - 'https://vault.kdev.intra/oidc/oidc/callback'
