base_url: oncall.kdev.intra
base_url_protocol: https


ingress:
  enabled: true
  className: default
  annotations:
    cert-manager.io/cluster-issuer: ca-issuer
    ingress.pomerium.io/allow_public_unauthenticated_access: 'true'
    #nginx.ingress.kubernetes.io/auth-signin: http://oauth.kdev.intra/oauth2/start
    ## That's what will be used in REAL LIFE
    ##nginx.ingress.kubernetes.io/auth-url: http://oauth.kdev.intra/oauth2/auth
    ## but because of https://github.com/kubernetes/ingress-nginx/issues/3665
    #nginx.ingress.kubernetes.io/auth-url: http://oauth2-proxy-ingress.ingress-system.svc.cluster.local/oauth2/auth
    #nginx.ingress.kubernetes.io/auth-response-headers: X-Auth-Request-User,X-Auth-Request-Email
    #nginx.ingress.kubernetes.io/proxy-buffer-size: 512k
    hajimari.io/enable: "true" 
    hajimari.io/group: "Monitoring"
    hajimari.io/appName: "Oncall"
    hajimari.io/icon: "mdi:bell-alert"
  hosts:
    - oncall.kdev.intra
  paths:
  - /
  pathType: ImplementationSpecific
  tls:
  - secretName: oncall-tls-secret
    hosts:
    - oncall.kdev.intra

ingress-nginx:
  enabled: false

cert-manager:
  enabled: false

database:
  type: mysql

grafana:
  enabled: false

externalGrafana:
  # Example: https://grafana.mydomain.com
  url: https://grafana.kdev.intra

networkPolicy:
  enabled: false