auth:
  createAdminUser: true
  adminUser: admin
  adminPassword: admin
  managementUser: manager
  managementPassword: manager
proxyAddressForwarding: true
ingress:
  enabled: true
  ingressClassName: "default"
  hostname: keycloak.kdev.intra
  annotations:
    cert-manager.io/cluster-issuer: ca-issuer
    ingress.pomerium.io/allow_public_unauthenticated_access: "true"
  tls: true
  extraTls:
  - hosts:
    - keycloak.kdev.intra
    secretName: keycloak-ingress-tls
cache:
  enabled: false
postgresql:
  enabled: false
  postgresqlPassword: password
externalDatabase:
  host: "none"
  password: "none"
extraEnvVars:
  - name: KEYCLOAK_DATABASE_VENDOR
    value: "dev-file"
#  - name: KEYCLOAK_EXTRA_ARGS
#    value: "--import-realm"
#extraVolumeMounts:
#- name: config-volume
#  mountPath: /opt/bitnami/keycloak/data/import/realm.json
#  subPath: realm.json
#extraVolumes:
#- name: config-volume
#  configMap:
#    name: keycloak-realm-config