log syslog notifications
frr defaults traditional
!
router bgp 64513
no bgp ebgp-requires-policy
bgp router-id 172.50.0.1
!
neighbor 172.50.0.2 remote-as 64512
neighbor 172.50.0.2 update-source 172.50.0.2
neighbor 172.50.0.2 soft-reconfiguration inbound
!
address-family ipv4 unicast
neighbor 172.50.0.2 next-hop-self
exit-address-family
!
address-family ipv6 unicast
exit-address-family
!
line vty
