crds:
  enabled: true
clusterResourceNamespace: "ingress-system"
resources:
  requests:
    cpu: 10m
    memory: 32Mi
prometheus:
  enabled: true
  servicemonitor:
    enabled: true
    namespace: "ingress-system"