authenticate:
  idp:
    provider: "oidc"
    url: ""
    clientID: "4af1fe3b73b43eaf9f9e"
    clientSecret: "4c32abcb6b6665cf45c0c71255a6f4b405123888"
    serviceAccount: "pomerium-authenticate"
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: ca-issuer
    tls:
      secretName: pomerium-ingress-tls
redis:
  enabled: false
  generateTLS: true
ingressController:
  enabled: true
  ingressClassResource:
    enabled: true
    default: true
    name: "default"
config:
  rootDomain: kdev.intra #Change this to your reserved domain space.
  generateTLS: true # On by default, disabled when cert-manager or another solution is in place.
ingress:
  enabled: false
metrics:
  enabled: true
  port: 9090
serviceMonitor:
  enabled: true
  namespace: ''
  labels:
    release: prometheus