authenticate:
  existingTLSSecret: pomerium-tls
  idp:
    provider: "oidc"
    url: "https://keycloak.kdev.intra/realms/kind-apps"
    clientID: "pomerium"
    clientSecret: "y5q5jeEpEmL7aJh74Tgsb32aJz1LaKAh"
    serviceAccount: "pomerium-authenticate"
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: ca-issuer
    tls:
      secretName: pomerium-ingress-tls
authorize:
  existingTLSSecret: pomerium-tls
databroker:
  existingTLSSecret: pomerium-tls
#  storage:
#    clientTLS:
#      existingSecretName: pomerium-redis-tls
#      existingCASecretKey: ca.crt
redis:
  enabled: false
  generateTLS: false # On by default, disabled when cert-manager or another solution
  tls:
    certificateSecret: pomerium-redis-tls
ingressController:
  enabled: true
  ingressClassResource:
    enabled: true
    default: true
    name: "default"
config:
  rootDomain: kdev.intra # Change this to your reserved domain space.
  generateTLS: false # On by default, disabled when cert-manager or another solution
  existingCASecret: pomerium-tls
ingress:
  enabled: false
proxy:
  existingTLSSecret: pomerium-tls
  service:
    type: "NodePort"
metrics:
  enabled: true
  port: 9090
serviceMonitor:
  enabled: true
  namespace: ''
  labels:
    release: prometheus