apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
networking:
  apiServerAddress: 127.0.0.1
  disableDefaultCNI: true
  ipFamily: ipv4
  kubeProxyMode: none
  podSubnet: 10.0.0.0/16
  serviceSubnet: 10.1.0.0/16
nodes:
- role: control-plane
kubeadmConfigPatches:
- |-
  kind: ClusterConfiguration
  apiServer:
    extraArgs:
      oidc-client-id: kind
      oidc-issuer-url: https://keycloak.kdev.intra/auth/realms/kind-apps
      oidc-username-claim: email
      oidc-groups-claim: groups
