apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
networking:
  apiServerAddress: 127.0.0.1
  disableDefaultCNI: true
  ipFamily: ipv4
  kubeProxyMode: none
  podSubnet: 10.0.0.0/16
  serviceSubnet: 10.1.0.0/16
nodes:
- role: control-plane
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."172.50.0.2:5000"]
    endpoint = ["http://172.50.0.2:5000"]
  [plugins."io.containerd.grpc.v1.cri".registry.configs."172.50.0.2:5000".tls]
    insecure_skip_verify = true
