kubeProxyReplacement: strict
k8sServiceHost: 192.168.0.15
k8sServicePort: 6443
rollOutCiliumPods: true
ipv4:
  enabled: true
ipv6:
  enabled: true
gatewayAPI:
  enabled: true
ingressController:
  enabled: false
hubble:
  metrics:
    serviceMonitor:
      enabled: true
    dashboards:
      enabled: true
      namespace: monitoring-system
      annotations:
        grafana_folder: Hubble
    enabled:
      - dns:query;ignoreAAAA
      - drop
      - tcp
      - flow
      - port-distribution
      - icmp
      - http
  ui:
    enabled: true
    replicas: 1
    ingress:
      enabled: true
      hosts:
        - hubble.k3s.intra
      annotations:
        kubernetes.io/ingress.class: pomerium
        cert-manager.io/cluster-issuer: ca-issuer
        ingress.pomerium.io/allow_any_authenticated_user: "true"
      tls:
      - secretName: hubble-ingress-tls
        hosts:
        - hubble.k3s.intra
    backend:
      resources:
        limits:
          cpu: 60m
          memory: 300Mi
        requests:
          cpu: 20m
          memory: 64Mi
    frontend:
      server:
        ipv6:
          enabled: false
      resources:
        limits:
          cpu: 1000m
          memory: 1024M
        requests:
          cpu: 100m
          memory: 64Mi
    proxy:
      resources:
        limits:
          cpu: 1000m
          memory: 1024M
        requests:
          cpu: 100m
          memory: 64Mi
  relay:
    enabled: true
    resources:
      limits:
        cpu: 100m
        memory: 500Mi
operator:
  replicas: 1
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
ipam:
  mode: cluster-pool
  operator:
    clusterPoolIPv4PodCIDR: 10.43.0.0/16
    clusterPoolIPv4MaskSize: 24
    clusterPoolIPv6PodCIDR: fd00::/104
    clusterPoolIPv6MaskSize: 120
resources:
  limits:
    cpu: 4000m
    memory: 4Gi
  requests:
    cpu: 100m
    memory: 512Mi
prometheus:
  enabled: true
  serviceMonitor:
    enabled: true

