MTU: 1300
externalIPs:
  enabled: true
hostPort:
  enabled: true
hubble:
  frontend:
    server:
      ipv6:
        enabled: false
  metrics:
    enabled:
    - dns
    - drop
    - tcp
    - flow:sourceContext=workload-name|reserved-identity;destinationContext=workload-name|reserved-identity
    - port-distribution
    - icmp
    - kafka:labelsContext=source_namespace,source_workload,destination_namespace,destination_workload,traffic_direction;sourceContext=workload-name|reserved-identity;destinationContext=workload-name|reserved-identity
    - policy:sourceContext=app|workload-name|pod|reserved-identity;destinationContext=app|workload-name|pod|dns|reserved-identity;labelsContext=source_namespace,destination_namespace
    - httpV2:exemplars=true;labelsContext=source_ip,source_namespace,source_workload,destination_ip,destination_namespace,destination_workload,traffic_direction
  relay:
    enabled: true
  ui:
    enabled: true
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: ca-issuer
        ingress.pomerium.io/allow_public_unauthenticated_access: 'true'
        nginx.ingress.kubernetes.io/auth-signin: http://oauth.kdev.intra/oauth2/start
        # That's what will be used in REAL LIFE
        #nginx.ingress.kubernetes.io/auth-url: http://oauth.kdev.intra/oauth2/auth
        # but because of https://github.com/kubernetes/ingress-nginx/issues/3665
        nginx.ingress.kubernetes.io/auth-url: http://oauth2-proxy-ingress.ingress-system.svc.cluster.local/oauth2/auth
        nginx.ingress.kubernetes.io/auth-response-headers: X-Auth-Request-User,X-Auth-Request-Email
        nginx.ingress.kubernetes.io/proxy-buffer-size: 512k
      className: default
      enabled: true
      hosts:
      - hubble.kdev.intra
      tls:
      - hosts:
        - hubble.kdev.intra
        secretName: hubble-ingress-tls
    replicas: 1
ipam:
  mode: kubernetes
ipv4:
  enabled: true
ipv6:
  enabled: false
k8sServiceHost: kdev-control-plane
k8sServicePort: '6443'
kubeProxyReplacement: true
l2announcements:
  enabled: true
loadBalancer:
  l7:
    backend: envoy
nodePort:
  enabled: true
operator:
  replicas: 1
pmtuDiscovery:
  enabled: true
rollOutCiliumPods: true
socketLB:
  enabled: true
  terminatePodConnections: true
