kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: csi-zfspv
  namespace: default
spec:
  storageClassName: openebs-zfspv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
